/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project_akhir;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class about extends javax.swing.JFrame {

    /** Creates new form about */
    public about() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 175));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(164, 164, 164));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(189, 189, 189));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/pcr.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 140, 400, 110);

        jLabel1.setFont(new java.awt.Font("Garamond", 0, 30)); // NOI18N
        jLabel1.setText("Project UAS Praktikum Pemograman Berorientasi Objek");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(370, 30, 665, 34);

        jLabel3.setFont(new java.awt.Font("Garamond", 0, 25)); // NOI18N
        jLabel3.setText("\"Pemesanan Tiket Travel Pada Cv. Jaya Sarolangun Travel\"");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(430, 70, 569, 29);

        jLabel4.setFont(new java.awt.Font("Garamond", 0, 23)); // NOI18N
        jLabel4.setText("Di Susun Oleh :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(620, 120, 144, 27);

        jLabel5.setFont(new java.awt.Font("Garamond", 0, 23)); // NOI18N
        jLabel5.setText("Oky Firnanda 2055301108");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(580, 180, 241, 45);

        jLabel6.setFont(new java.awt.Font("Garamond", 0, 23)); // NOI18N
        jLabel6.setText("Dosen Pengampu / AIL :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(580, 250, 250, 27);

        jLabel7.setFont(new java.awt.Font("Garamond", 0, 23)); // NOI18N
        jLabel7.setText("Endah Chilfani, S. S. T");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(590, 320, 210, 27);

        jLabel8.setFont(new java.awt.Font("Garamond", 0, 23)); // NOI18N
        jLabel8.setText("Nadia Rajagukguk 2055301102");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(550, 150, 276, 45);

        jLabel9.setFont(new java.awt.Font("Garamond", 0, 23)); // NOI18N
        jLabel9.setText("Puja Hanifah, S. S. T., M. MSI.");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(560, 290, 273, 27);

        jLabel10.setFont(new java.awt.Font("Garamond", 0, 30)); // NOI18N
        jLabel10.setText("Program Studi D4- Teknik Informatika");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(480, 380, 470, 34);

        jLabel11.setFont(new java.awt.Font("Garamond", 0, 30)); // NOI18N
        jLabel11.setText("Jurusan Teknologi Informasi");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(540, 420, 350, 34);

        jLabel12.setFont(new java.awt.Font("Garamond", 0, 30)); // NOI18N
        jLabel12.setText("Politeknik Caltex Riau");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(580, 450, 380, 50);

        jLabel13.setFont(new java.awt.Font("Garamond", 0, 30)); // NOI18N
        jLabel13.setText("TA 2020/2021");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(630, 500, 200, 34);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/Logo-2.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(140, 270, 200, 190);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 60, 1080, 580);

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/close_delete.png"))); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });
        jPanel1.add(btnTutup);
        btnTutup.setBounds(1150, 10, 50, 41);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar?",
            "Yakin", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        this.dispose();
        }
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new about().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
